loguru:
  main:
    sink: './log/contest_predictor_main.log'
    level: INFO
    rotation: 'saturday at 12:00'
  api:
    sink: './log/api/contest_predictor_api.log'
    level: INFO
    rotation: '00:00'

fastapi:
  CORS_allow_origins:
    - "http://localhost:3000"
